### PR TITLE
Thread urls now contain the post title as the slug

### PR DESCRIPTION
**Pull request by jeremyphilemon**
- This is done for better readability of the urls and SEO.
- I've updated the sitemap.xml to display the slugged urls to web crawlers.

### CODE REVIEW

**Comment by jeremyphilemon** [comment]
@digi0ps Need tests to check if all the views are working.

**Comment by jeremyphilemon** [comment]
@digi0ps Were you able to reproduce the above 404?

**Comment by digi0ps** [comment]
No I wasn't able to migrate. It works fine for me..

**Comment by jeremyphilemon** [comment]
@digi0ps Can we merge this?

**Comment by digi0ps** [comment]
I made a comment about the two slug url entries...
Are we gonna use `/thread/slug` or `/thread-slug`?

**Pull request merged**
